opt_in_rules:
  - private_action
  - private_outlet
disabled_rules:
  - trailing_comma
  - empty_enum_arguments
  - void_return
  - redundant_optional_initialization
  - nesting
  - redundant_discardable_let
excluded: 
  - "Sources/BattleNetKit/Packets/Aurora/*"
  - "Tools/*/*"
  - ".build/*/*"
  - ".swiftpm/*/*"
line_length:
  warning: 140
  error: 140
identifier_name:
  excluded:
    - "id"
    - "on"
type_name:
  max_length: 60
