// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: aurora/global_extensions/routing.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Bgs_Protocol_ClientIdentityRoutingType: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case clientIdentityRoutingDisabled // = 0
  case clientIdentityRoutingBattleNetAccount // = 1
  case clientIdentityRoutingGameAccount // = 2
  case clientIdentityRoutingInstanceID // = 3

  public init() {
    self = .clientIdentityRoutingDisabled
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .clientIdentityRoutingDisabled
    case 1: self = .clientIdentityRoutingBattleNetAccount
    case 2: self = .clientIdentityRoutingGameAccount
    case 3: self = .clientIdentityRoutingInstanceID
    default: return nil
    }
  }

  public var rawValue: Int {
    switch self {
    case .clientIdentityRoutingDisabled: return 0
    case .clientIdentityRoutingBattleNetAccount: return 1
    case .clientIdentityRoutingGameAccount: return 2
    case .clientIdentityRoutingInstanceID: return 3
    }
  }

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Bgs_Protocol_ClientIdentityRoutingType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "CLIENT_IDENTITY_ROUTING_DISABLED"),
    1: .same(proto: "CLIENT_IDENTITY_ROUTING_BATTLE_NET_ACCOUNT"),
    2: .same(proto: "CLIENT_IDENTITY_ROUTING_GAME_ACCOUNT"),
    3: .same(proto: "CLIENT_IDENTITY_ROUTING_INSTANCE_ID"),
  ]
}
