// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: LogonQueueUpdateRequest.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct LogonQueueUpdateRequest: SwiftProtobuf.Message {
  public static let protoMessageName: String = "LogonQueueUpdateRequest"

  public var position: UInt32 {
    get {return _position ?? 0}
    set {_position = newValue}
  }
  /// Returns true if `position` has been explicitly set.
  public var hasPosition: Bool {return self._position != nil}
  /// Clears the value of `position`. Subsequent reads from it will return its default value.
  public mutating func clearPosition() {self._position = nil}

  public var estimatedTime: UInt64 {
    get {return _estimatedTime ?? 0}
    set {_estimatedTime = newValue}
  }
  /// Returns true if `estimatedTime` has been explicitly set.
  public var hasEstimatedTime: Bool {return self._estimatedTime != nil}
  /// Clears the value of `estimatedTime`. Subsequent reads from it will return its default value.
  public mutating func clearEstimatedTime() {self._estimatedTime = nil}

  public var etaDeviationInSec: UInt64 {
    get {return _etaDeviationInSec ?? 0}
    set {_etaDeviationInSec = newValue}
  }
  /// Returns true if `etaDeviationInSec` has been explicitly set.
  public var hasEtaDeviationInSec: Bool {return self._etaDeviationInSec != nil}
  /// Clears the value of `etaDeviationInSec`. Subsequent reads from it will return its default value.
  public mutating func clearEtaDeviationInSec() {self._etaDeviationInSec = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  public var isInitialized: Bool {
    if self._position == nil {return false}
    if self._estimatedTime == nil {return false}
    if self._etaDeviationInSec == nil {return false}
    return true
  }

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularUInt32Field(value: &self._position)
      case 2: try decoder.decodeSingularUInt64Field(value: &self._estimatedTime)
      case 3: try decoder.decodeSingularUInt64Field(value: &self._etaDeviationInSec)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._position {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    }
    if let v = self._estimatedTime {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 2)
    }
    if let v = self._etaDeviationInSec {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  fileprivate var _position: UInt32? = nil
  fileprivate var _estimatedTime: UInt64? = nil
  fileprivate var _etaDeviationInSec: UInt64? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension LogonQueueUpdateRequest: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "position"),
    2: .standard(proto: "estimated_time"),
    3: .standard(proto: "eta_deviation_in_sec"),
  ]

  public func _protobuf_generated_isEqualTo(other: LogonQueueUpdateRequest) -> Bool {
    if self._position != other._position {return false}
    if self._estimatedTime != other._estimatedTime {return false}
    if self._etaDeviationInSec != other._etaDeviationInSec {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}
