// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: aurora/api/client/v2/channel_enum.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Bgs_Protocol_Channel_V2_PrivacyLevel: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case `open` // = 1
  case openInvitation // = 3
  case closed // = 4

  public init() {
    self = .open
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 1: self = .open
    case 3: self = .openInvitation
    case 4: self = .closed
    default: return nil
    }
  }

  public var rawValue: Int {
    switch self {
    case .open: return 1
    case .openInvitation: return 3
    case .closed: return 4
    }
  }

}

public enum Bgs_Protocol_Channel_V2_ChannelRemovedReason: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case memberLeft // = 0
  case memberKicked // = 1
  case dissolvedByMember // = 2
  case memberDisconnected // = 3
  case memberRemovedByService // = 4
  case dissolvedByService // = 5
  case disconnected // = 6
  case founderLeft // = 14

  public init() {
    self = .memberLeft
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .memberLeft
    case 1: self = .memberKicked
    case 2: self = .dissolvedByMember
    case 3: self = .memberDisconnected
    case 4: self = .memberRemovedByService
    case 5: self = .dissolvedByService
    case 6: self = .disconnected
    case 14: self = .founderLeft
    default: return nil
    }
  }

  public var rawValue: Int {
    switch self {
    case .memberLeft: return 0
    case .memberKicked: return 1
    case .dissolvedByMember: return 2
    case .memberDisconnected: return 3
    case .memberRemovedByService: return 4
    case .dissolvedByService: return 5
    case .disconnected: return 6
    case .founderLeft: return 14
    }
  }

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Bgs_Protocol_Channel_V2_PrivacyLevel: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "PRIVACY_LEVEL_OPEN"),
    3: .same(proto: "PRIVACY_LEVEL_OPEN_INVITATION"),
    4: .same(proto: "PRIVACY_LEVEL_CLOSED"),
  ]
}

extension Bgs_Protocol_Channel_V2_ChannelRemovedReason: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "CHANNEL_REMOVED_REASON_MEMBER_LEFT"),
    1: .same(proto: "CHANNEL_REMOVED_REASON_MEMBER_KICKED"),
    2: .same(proto: "CHANNEL_REMOVED_REASON_DISSOLVED_BY_MEMBER"),
    3: .same(proto: "CHANNEL_REMOVED_REASON_MEMBER_DISCONNECTED"),
    4: .same(proto: "CHANNEL_REMOVED_REASON_MEMBER_REMOVED_BY_SERVICE"),
    5: .same(proto: "CHANNEL_REMOVED_REASON_DISSOLVED_BY_SERVICE"),
    6: .same(proto: "CHANNEL_REMOVED_REASON_DISCONNECTED"),
    14: .same(proto: "CHANNEL_REMOVED_REASON_FOUNDER_LEFT"),
  ]
}
